import BugBountyTable from "@/components/home/BugBounty";
import Head from "next/head";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "VigilSeek - Bug Bounty Programs",
  description: "Generated by create next app",
};

export default function Page() {
  return (
    <div className="flex flex-col gap-8">
      <BugBountyTable />
    </div>
  );
}
