name: Deploy on PR merge to main

on:
  pull_request:
    types:
      - closed

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore .env from GitHub Secrets
        run: echo "$ENV_FILE" > .env
        env:
          ENV_FILE: ${{ secrets.ENV_FILE }}

      - name: Check for changes in package.json or package-lock.json
        id: check_changes
        run: |
          if git diff --name-only HEAD^ HEAD | grep -qE 'package(-lock)?\.json'; then
            echo "RUN_NPM_INSTALL=true" >> $GITHUB_ENV
          fi

      - name: Update npm dependencies (if required)
        if: env.RUN_NPM_INSTALL == 'true'
        run: |
          npm install
          npm run build

      - name: Run deployment script
        run: ./deploy.sh
