name: Deploy on PR merge to main

on:
  pull_request:
    types:
      - closed

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Створення .env файлу
        run: |
          echo "NEXT_PUBLIC_BACKEND_URL=${{ vars.NEXT_PUBLIC_BACKEND_URL }}" > .env
          echo "NEXT_PUBLIC_TG_URL=${{ vars.NEXT_PUBLIC_TG_URL }}" >> .env
          echo "NEXT_PUBLIC_X_URL=${{ vars.NEXT_PUBLIC_X_URL }}" >> .env

      - name: Кешування npm та Next.js кешу збірки
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - name: Перевстановлення залежностей (якщо потрібно)
        run: npm install --legacy-peer-deps

      - name: Збірка проекту
        run: |
          export PATH="./node_modules/.bin:$PATH"
          npx next build && npx next-nginx-routes

      - name: Копіювання файлів у /var/www/vigilseekFrontend/out
        run: sudo cp -R out/* /var/www/vigilseekFrontend/out/
