name: Deploy on PR merge to main

on:
  pull_request:
    types:
      - closed

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Завантажуємо два останніх коміти для перевірки змін

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Check if package.json or package-lock.json changed
        id: check-files
        run: |
          if git diff --name-only HEAD^ HEAD -- package.json package-lock.json | grep -qE 'package(-lock)?\.json'; then
            echo "RUN_NPM_INSTALL=true" >> $GITHUB_ENV
          else
            echo "RUN_NPM_INSTALL=false" >> $GITHUB_ENV
          fi

      - name: Install dependencies (if needed)
        if: env.RUN_NPM_INSTALL == 'true'
        run: npm install

      - name: Deploy
        run: sudo ./deploy.sh
